version: '3.8'

services:
  # Redis (セッション管理・キャッシュ) - 最初に起動
  redis:
    image: redis:7-alpine
    container_name: master-data-redis
    ports:
      - "6379:6379"
    networks:
      - master-data-network
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass redis123

  # データベース層 (PostgreSQL)
  database:
    image: postgres:15-alpine
    container_name: master-data-db
    environment:
      POSTGRES_DB: master_data
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"
    networks:
      - master-data-network
    restart: unless-stopped
    depends_on:
      - redis

  # アプリケーション層 (Node.js API)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: master-data-api
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: master_data
      DB_USER: admin
      DB_PASSWORD: admin123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis123
      JWT_SECRET: your-jwt-secret-key-change-in-production
      CORS_ORIGIN: http://localhost:8080
      LOG_LEVEL: info
    ports:
      - "3000:3000"
    depends_on:
      - database
      - redis
    networks:
      - master-data-network
    restart: unless-stopped
    volumes:
      - ./api/logs:/app/logs:Z

  # プレゼンテーション層 (React Frontend)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: master-data-frontend
    environment:
      VITE_API_URL: http://localhost:3000/api
    ports:
      - "8080:8080"
    depends_on:
      - api
    networks:
      - master-data-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  master-data-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16