apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: master-data-maintenance-build
  labels:
    app: master-data-maintenance
spec:
  source:
    type: Git
    git:
      uri: https://github.com/your-username/master-data-maintenance.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: master-data-maintenance:latest
  triggers:
  - type: ConfigChange
  - type: GitHub
    github:
      secret: github-webhook-secret
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: master-data-maintenance
  labels:
    app: master-data-maintenance
spec:
  lookupPolicy:
    local: false